### ISSUE TITLE
getRatesWithShipment doesn't map customsItem object correctly

### ISSUE THREAD

**Issue by Renzik** [ShipEngine/shipengine-js#189] opened 2022-08-31 20:13 UTC
`function mapCustoms(params) {
    if (!params)
        return undefined;
    let custom_items = [];
    if (params.customsItems) {
        console.log('customsItems', params.customsItems);
        custom_items = params.customsItems.map((customItem) => ({
            quantity: customItem.quantity,
            value: customItem.value,
            harmonized_tariff_code: customItem.harmonizedTariffCode,
            country_of_origin: customItem.countryOfOrigin,
            unit_of_measure: customItem.unitOfMeasure,
            sku: customItem.sku,
            sku_description: customItem.skuDescription,
        }));
    }
    return {
        contents: params.contents,
        non_delivery: params.nonDelivery,
        customs_items: custom_items,
    };
}`

There's no description being mapped and it's necessary to calculate international shipment shipping rates.

**Comment by AnneOReilly** [comment] 2022-08-31 20:34
Thank you for this report!  We will queue this for resolution in the next release.

**Comment by Renzik** [comment] 2022-08-31 23:58
> Thank you for this report! We will queue this for resolution in the next release.

Thank you for listening. Also, sorry for the messy copy pasta of the mapCustoms func.

**Comment by sushithegreat** [comment] 2022-09-22 21:06
@Renzik I believe this was a duplicate of [185](https://github.com/ShipEngine/shipengine-js/issues/185) and was fixed in [this PR](https://github.com/ShipEngine/shipengine-js/pull/186)

**Closed by sushithegreat** 2022-09-22 21:06 UTC
